services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi_web
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - .:/app
    command: uvicorn tests.frontend.fastapi_main:app --host 0.0.0.0 --port 3000 --reload
    ports:
      - "3000:3000"

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - .:/app
    # слушаем обе очереди
    command: celery -A tests.frontend.tasks worker --loglevel=info -Q high_priority,low_priority

  beat:
    build: .
    container_name: celery_beat
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A tests.frontend.celery_app.celery beat --loglevel=info