version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi_web
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - .:/app
    command: uvicorn tests.frontend.fastapi_main:app --host 0.0.0.0 --port 3000 --reload
    ports:
      - "3000:3000"

  worker:
    build: .
    container_name: rq_worker
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    volumes:
      - .:/app
    # слушаем очередь "default"
    command: rq worker -u redis://redis:6379 default


